services:
  space_ros_isaac_sim:
    build:
      context: .
      dockerfile: Dockerfile
    image: openrobotics/space_ros_isaac_sim
    container_name: space_ros_isaac_sim
    network_mode: host
    runtime: nvidia
    privileged: true
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - OMNI_KIT_ACCEPT_EULA=Y
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - XDG_RUNTIME_DIR=/run/user/1000
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - isaac-cache:/home/spaceros-user/.isaac-sim-cache:rw
      - ../curiosity_sim:/home/spaceros-user/curiosity_sim:rw
      - ../lidar_configs/CuriosityLidar.json:/usr/local/lib/python3.10/dist-packages/isaacsim/exts/omni.isaac.sensor/data/lidar_configs/CuriosityLidar.json:ro
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  isaac-cache:
